### PR TITLE
Issue#63 match titles

### LINKED ISSUE #63: Match ViewData Titles
ViewData Titles on pages should match the page title. Ex: The title "index" of the resources page should be "Resources" not "index".

### PR DESCRIPTION
**Pull request by MitchellCodes**
Closes #63

### CODE REVIEW

**Review by Tinet0624 — DISMISSED** [review]
The changes you made were great but the rest of the pages need to be gone through and made to match. Also there are more index pages like the one in the example on the pull request that also need to have their titles changed.

**Comment by MitchellCodes** [comment]
I must have misread the issue's description. In the example you gave, did you mean the index of the resources page should have the file name changed to Resources.cshtml instead of Index.cshtml?

**Comment by Tinet0624** [comment]
You've done what was needed for the parts you fixed but the rest of the site needs those same changes.  If you look at the "About" section of the site, you'll notice that the page titles are the same as the others and need to be fixed.  There is no need to change the file names, just the page titles, ViewData[Title] = "Your Title Here".

**Comment by MitchellCodes** [comment]
I went back through and changed the h1 elements to use ViewData["Title"] for nearly every page. The pages I did not do this on are some CRUD pages for Agency and About (edit, and delete pages say the name of the entity) and the program videos page.

**Review by JoeProgrammer88 — APPROVED** [review]
Thanks for changing all those links

**Pull request merged**
